// <auto-generated>
//   Generated by tools/gen_strings.py from src/MegaPDF.Avalonia/Strings/Strings.resx.
//   Do not edit: change the catalogue and re-run the script.
// </auto-generated>
#nullable enable
using System.Globalization;

namespace MegaPDF.Avalonia;

/// <summary>
/// Typed access to the English catalogue's keys (#91). Every user-facing string
/// in code goes through here, so a missing key is a compile error rather than a
/// runtime blank.
/// </summary>
public static partial class Strings
{
    private static readonly System.Resources.ResourceManager Manager =
        new("MegaPDF.Avalonia.Strings.Strings", typeof(Strings).Assembly);

    private static string Get(string key) =>
        Manager.GetString(key, CultureInfo.CurrentUICulture) ?? key;

    /// <summary>Open</summary>
    public static string Open => Get("Open");

    /// <summary>Open a PDF</summary>
    public static string OpenAPdf => Get("OpenAPdf");

    /// <summary>Open a PDF…</summary>
    public static string OpenAPdfEllipsis => Get("OpenAPdfEllipsis");

    /// <summary>Save</summary>
    public static string Save => Get("Save");

    /// <summary>Save As</summary>
    public static string SaveAs => Get("SaveAs");

    /// <summary>Save a copy</summary>
    public static string SaveACopy => Get("SaveACopy");

    /// <summary>Save a smaller copy</summary>
    public static string SaveASmallerCopy => Get("SaveASmallerCopy");

    /// <summary>Save a smaller copy for email</summary>
    public static string SaveSmallerCopyForEmail => Get("SaveSmallerCopyForEmail");

    /// <summary>Shrink</summary>
    public static string Shrink => Get("Shrink");

    /// <summary>Print</summary>
    public static string Print => Get("Print");

    /// <summary>Sign</summary>
    public static string Sign => Get("Sign");

    /// <summary>Add text</summary>
    public static string AddText => Get("AddText");

    /// <summary>Cover</summary>
    public static string Cover => Get("Cover");

    /// <summary>Undo</summary>
    public static string Undo => Get("Undo");

    /// <summary>Redo</summary>
    public static string Redo => Get("Redo");

    /// <summary>Zoom out</summary>
    public static string ZoomOut => Get("ZoomOut");

    /// <summary>Zoom in</summary>
    public static string ZoomIn => Get("ZoomIn");

    /// <summary>Actual size</summary>
    public static string ActualSize => Get("ActualSize");

    /// <summary>Fit width</summary>
    public static string FitWidth => Get("FitWidth");

    /// <summary>Fit page</summary>
    public static string FitPage => Get("FitPage");

    /// <summary>Options</summary>
    public static string Options => Get("Options");

    /// <summary>Recent</summary>
    public static string Recent => Get("Recent");

    /// <summary>Fill in a form, tick the boxes, sign it, and save.</summary>
    public static string EmptyStateTagline => Get("EmptyStateTagline");

    /// <summary>Your signatures</summary>
    public static string YourSignatures => Get("YourSignatures");

    /// <summary>Nothing saved yet — draw one below.</summary>
    public static string NoSignaturesYet => Get("NoSignaturesYet");

    /// <summary>Draw a new signature…</summary>
    public static string DrawNewSignature => Get("DrawNewSignature");

    /// <summary>Use a photo of your signature…</summary>
    public static string UsePhotoOfSignature => Get("UsePhotoOfSignature");

    /// <summary>Choose a photo of your signature</summary>
    public static string ChoosePhotoOfSignature => Get("ChoosePhotoOfSignature");

    /// <summary>Signature</summary>
    public static string SignatureDefaultName => Get("SignatureDefaultName");

    /// <summary>Tick marks look like</summary>
    public static string TickMarksLookLike => Get("TickMarksLookLike");

    /// <summary>Cross</summary>
    public static string MarkStyleCross => Get("MarkStyleCross");

    /// <summary>Check</summary>
    public static string MarkStyleCheck => Get("MarkStyleCheck");

    /// <summary>Filled square</summary>
    public static string MarkStyleFilledSquare => Get("MarkStyleFilledSquare");

    /// <summary>Flatten when saving</summary>
    public static string FlattenWhenSaving => Get("FlattenWhenSaving");

    /// <summary>Flattening bakes ticks and signatures into the page. They cannot be moved or removed afterwards.</summary>
    public static string FlattenExplanation => Get("FlattenExplanation");

    /// <summary>Find in document</summary>
    public static string FindInDocument => Get("FindInDocument");

    /// <summary>Previous</summary>
    public static string Previous => Get("Previous");

    /// <summary>Next</summary>
    public static string Next => Get("Next");

    /// <summary>Done</summary>
    public static string Done => Get("Done");

    /// <summary>Not found</summary>
    public static string NotFound => Get("NotFound");

    /// <summary>{0} of {1}</summary>
    public static string MatchOf(object? arg0, object? arg1) => string.Format(CultureInfo.CurrentCulture, Get("MatchOf"), arg0, arg1);

    /// <summary>Page {0} of {1}</summary>
    public static string PageOf(object? arg0, object? arg1) => string.Format(CultureInfo.CurrentCulture, Get("PageOf"), arg0, arg1);

    /// <summary>{0} — MegaPDF</summary>
    public static string WindowTitleFormat(object? arg0) => string.Format(CultureInfo.CurrentCulture, Get("WindowTitleFormat"), arg0);

    /// <summary>Click where the new text should go — Esc cancels</summary>
    public static string ModeHintAddText => Get("ModeHintAddText");

    /// <summary>Drag over what you want to cover — Esc cancels</summary>
    public static string ModeHintWhiteout => Get("ModeHintWhiteout");

    /// <summary>Click where the signature should go — Esc cancels</summary>
    public static string ModeHintPlaceSignature => Get("ModeHintPlaceSignature");

    /// <summary>Type, then press Enter</summary>
    public static string TypeThenEnter => Get("TypeThenEnter");

    /// <summary>Open a PDF to get started.</summary>
    public static string OpenToGetStarted => Get("OpenToGetStarted");

    /// <summary>This PDF is password-protected.</summary>
    public static string PdfIsPasswordProtected => Get("PdfIsPasswordProtected");

    /// <summary>That password did not work.</summary>
    public static string PasswordDidNotWork => Get("PasswordDidNotWork");

    /// <summary>That file could not be read.</summary>
    public static string FileCouldNotBeRead => Get("FileCouldNotBeRead");

    /// <summary>That file is not a valid PDF.</summary>
    public static string FileNotValidPdf => Get("FileNotValidPdf");

    /// <summary>That file could not be opened (error {0}).</summary>
    public static string FileCouldNotBeOpened(object? arg0) => string.Format(CultureInfo.CurrentCulture, Get("FileCouldNotBeOpened"), arg0);

    /// <summary>Opening cancelled.</summary>
    public static string OpeningCancelled => Get("OpeningCancelled");

    /// <summary>{0} — {1} page. Click a checkbox to tick it.</summary>
    public static string DocumentOpenedOne(object? arg0, object? arg1) => string.Format(CultureInfo.CurrentCulture, Get("DocumentOpenedOne"), arg0, arg1);

    /// <summary>{0} — {1} pages. Click a checkbox to tick it.</summary>
    public static string DocumentOpenedOther(object? arg0, object? arg1) => string.Format(CultureInfo.CurrentCulture, Get("DocumentOpenedOther"), arg0, arg1);

    /// <summary>That file is not on the local disk. Copy it somewhere local and try again.</summary>
    public static string FileNotLocal => Get("FileNotLocal");

    /// <summary>That file has moved or been deleted. Open it again to restore access.</summary>
    public static string FileMovedOrDeleted => Get("FileMovedOrDeleted");

    /// <summary>That file cannot be opened for editing from here. Use Open to pick it again.</summary>
    public static string FileCannotBeOpenedFromHere => Get("FileCannotBeOpenedFromHere");

    /// <summary>Ready.</summary>
    public static string Ready => Get("Ready");

    /// <summary>Checkbox toggled.</summary>
    public static string CheckboxToggled => Get("CheckboxToggled");

    /// <summary>Checked.</summary>
    public static string Checked => Get("Checked");

    /// <summary>Unchecked.</summary>
    public static string Unchecked => Get("Unchecked");

    /// <summary>Undone.</summary>
    public static string Undone => Get("Undone");

    /// <summary>Redone.</summary>
    public static string Redone => Get("Redone");

    /// <summary>Text edited.</summary>
    public static string TextEdited => Get("TextEdited");

    /// <summary>Text edited — the original font could not write that, so a close match was used.</summary>
    public static string TextEditedSubstitutedFont => Get("TextEditedSubstitutedFont");

    /// <summary>That text is part of a scanned image, so it cannot be edited. You can cover it and type over the top instead.</summary>
    public static string TextIsScanned => Get("TextIsScanned");

    /// <summary>That text uses a font that cannot write those characters, and no close substitute was available.</summary>
    public static string TextFontCannotWrite => Get("TextFontCannotWrite");

    /// <summary>Field cleared.</summary>
    public static string FieldCleared => Get("FieldCleared");

    /// <summary>Field filled.</summary>
    public static string FieldFilled => Get("FieldFilled");

    /// <summary>Text deleted.</summary>
    public static string TextDeleted => Get("TextDeleted");

    /// <summary>Text updated.</summary>
    public static string TextUpdated => Get("TextUpdated");

    /// <summary>Text moved.</summary>
    public static string TextMoved => Get("TextMoved");

    /// <summary>Text added.</summary>
    public static string TextAdded => Get("TextAdded");

    /// <summary>Text removed.</summary>
    public static string TextRemoved => Get("TextRemoved");

    /// <summary>"{0}" is not one of the three available faces.</summary>
    public static string FontNotAvailable(object? arg0) => string.Format(CultureInfo.CurrentCulture, Get("FontNotAvailable"), arg0);

    /// <summary>Covered.</summary>
    public static string Covered => Get("Covered");

    /// <summary>Cover removed.</summary>
    public static string CoverRemoved => Get("CoverRemoved");

    /// <summary>Signature moved.</summary>
    public static string SignatureMoved => Get("SignatureMoved");

    /// <summary>Signature removed.</summary>
    public static string SignatureRemoved => Get("SignatureRemoved");

    /// <summary>Signature deleted.</summary>
    public static string SignatureDeleted => Get("SignatureDeleted");

    /// <summary>Drag to move, corners to resize, Delete to remove.</summary>
    public static string SignatureSelectedHint => Get("SignatureSelectedHint");

    /// <summary>Drag to move, double-click to edit, Delete to remove.</summary>
    public static string TextBoxSelectedHint => Get("TextBoxSelectedHint");

    /// <summary>Press Delete to remove this cover.</summary>
    public static string CoverSelectedHint => Get("CoverSelectedHint");

    /// <summary>Nothing on this document can be changed from the keyboard.</summary>
    public static string NothingKeyboardEditable => Get("NothingKeyboardEditable");

    /// <summary>Checkbox, ticked</summary>
    public static string RegionCheckboxTicked => Get("RegionCheckboxTicked");

    /// <summary>Checkbox, not ticked</summary>
    public static string RegionCheckboxNotTicked => Get("RegionCheckboxNotTicked");

    /// <summary>Box to tick</summary>
    public static string RegionBoxToTick => Get("RegionBoxToTick");

    /// <summary>Form field</summary>
    public static string RegionFormField => Get("RegionFormField");

    /// <summary>Text, editable</summary>
    public static string RegionTextEditable => Get("RegionTextEditable");

    /// <summary>Added text</summary>
    public static string RegionAddedText => Get("RegionAddedText");

    /// <summary>Signature or tick mark</summary>
    public static string RegionSignatureOrMark => Get("RegionSignatureOrMark");

    /// <summary>Cover</summary>
    public static string RegionCover => Get("RegionCover");

    /// <summary>Page</summary>
    public static string RegionPage => Get("RegionPage");

    /// <summary>Page {0}, {1}</summary>
    public static string PageRegionDescription(object? arg0, object? arg1) => string.Format(CultureInfo.CurrentCulture, Get("PageRegionDescription"), arg0, arg1);

    /// <summary>Saved the signature "{0}". Click where it should go.</summary>
    public static string SignatureSavedClickToPlace(object? arg0) => string.Format(CultureInfo.CurrentCulture, Get("SignatureSavedClickToPlace"), arg0);

    /// <summary>Click where "{0}" should go.</summary>
    public static string ClickWhereSignatureGoes(object? arg0) => string.Format(CultureInfo.CurrentCulture, Get("ClickWhereSignatureGoes"), arg0);

    /// <summary>Placed "{0}".</summary>
    public static string PlacedSignature(object? arg0) => string.Format(CultureInfo.CurrentCulture, Get("PlacedSignature"), arg0);

    /// <summary>Placement cancelled.</summary>
    public static string PlacementCancelled => Get("PlacementCancelled");

    /// <summary>Could not read that signature.</summary>
    public static string CouldNotReadSignature => Get("CouldNotReadSignature");

    /// <summary>Could not read that image.</summary>
    public static string CouldNotReadImage => Get("CouldNotReadImage");

    /// <summary>Could not save that signature.</summary>
    public static string CouldNotSaveSignature => Get("CouldNotSaveSignature");

    /// <summary>Saved {0}.</summary>
    public static string SavedFile(object? arg0) => string.Format(CultureInfo.CurrentCulture, Get("SavedFile"), arg0);

    /// <summary>Saved {0}. It cannot be shrunk from here — reopen it first.</summary>
    public static string SavedCannotShrink(object? arg0) => string.Format(CultureInfo.CurrentCulture, Get("SavedCannotShrink"), arg0);

    /// <summary>Could not save.</summary>
    public static string CouldNotSave => Get("CouldNotSave");

    /// <summary>The saved document could not be read back, so the original was left untouched.</summary>
    public static string SavedDocumentUnreadable => Get("SavedDocumentUnreadable");

    /// <summary>There is nowhere to save this back to. Use Save As to choose a file.</summary>
    public static string NowhereToSave => Get("NowhereToSave");

    /// <summary>{0} copy</summary>
    public static string SuggestedCopyName(object? arg0) => string.Format(CultureInfo.CurrentCulture, Get("SuggestedCopyName"), arg0);

    /// <summary>{0} - smaller</summary>
    public static string SuggestedSmallerName(object? arg0) => string.Format(CultureInfo.CurrentCulture, Get("SuggestedSmallerName"), arg0);

    /// <summary>document</summary>
    public static string DefaultDocumentName => Get("DefaultDocumentName");

    /// <summary>PDF document</summary>
    public static string PdfDocument => Get("PdfDocument");

    /// <summary>Save your changes first, then shrink the saved file.</summary>
    public static string SaveBeforeShrinking => Get("SaveBeforeShrinking");

    /// <summary>Reopen this document before shrinking it.</summary>
    public static string ReopenBeforeShrinking => Get("ReopenBeforeShrinking");

    /// <summary>The pictures in this document are already small — nothing to shrink.</summary>
    public static string NothingToShrink => Get("NothingToShrink");

    /// <summary>Saved a smaller copy: {0} picture re-encoded.</summary>
    public static string SmallerCopySavedOne(object? arg0) => string.Format(CultureInfo.CurrentCulture, Get("SmallerCopySavedOne"), arg0);

    /// <summary>Saved a smaller copy: {0} pictures re-encoded.</summary>
    public static string SmallerCopySavedOther(object? arg0) => string.Format(CultureInfo.CurrentCulture, Get("SmallerCopySavedOther"), arg0);

    /// <summary>Could not shrink.</summary>
    public static string CouldNotShrink => Get("CouldNotShrink");

    /// <summary>Printing from this build is available on macOS only.</summary>
    public static string PrintingMacOnly => Get("PrintingMacOnly");

    /// <summary>Could not print.</summary>
    public static string CouldNotPrint => Get("CouldNotPrint");

    /// <summary>Could not load the system printing components.</summary>
    public static string PrintComponentsNotLoaded => Get("PrintComponentsNotLoaded");

    /// <summary>The system print components are unavailable.</summary>
    public static string PrintComponentsUnavailable => Get("PrintComponentsUnavailable");

    /// <summary>The document path could not be prepared.</summary>
    public static string PrintPathNotPrepared => Get("PrintPathNotPrepared");

    /// <summary>The document could not be prepared for printing.</summary>
    public static string PrintDocumentNotPrepared => Get("PrintDocumentNotPrepared");

    /// <summary>The print operation could not be created.</summary>
    public static string PrintOperationNotCreated => Get("PrintOperationNotCreated");

    /// <summary>Sent to the printer.</summary>
    public static string SentToPrinter => Get("SentToPrinter");

    /// <summary>Printing cancelled.</summary>
    public static string PrintingCancelled => Get("PrintingCancelled");

    /// <summary>Recovered {0} unsaved change to {1}.</summary>
    public static string RecoveredChangesOne(object? arg0, object? arg1) => string.Format(CultureInfo.CurrentCulture, Get("RecoveredChangesOne"), arg0, arg1);

    /// <summary>Recovered {0} unsaved changes to {1}.</summary>
    public static string RecoveredChangesOther(object? arg0, object? arg1) => string.Format(CultureInfo.CurrentCulture, Get("RecoveredChangesOther"), arg0, arg1);

    /// <summary>Reopened {0}; there was nothing left to recover.</summary>
    public static string ReopenedNothingToRecover(object? arg0) => string.Format(CultureInfo.CurrentCulture, Get("ReopenedNothingToRecover"), arg0);

    /// <summary>Discarded the unsaved changes.</summary>
    public static string DiscardedUnsavedChanges => Get("DiscardedUnsavedChanges");

    /// <summary>Unsaved changes</summary>
    public static string UnsavedChanges => Get("UnsavedChanges");

    /// <summary>MegaPDF closed with unsaved changes to "{0}".</summary>
    public static string RecoveryHeadline(object? arg0) => string.Format(CultureInfo.CurrentCulture, Get("RecoveryHeadline"), arg0);

    /// <summary>{0} change was made and never saved, last on {1}.</summary>
    public static string RecoveryChangesOne(object? arg0, object? arg1) => string.Format(CultureInfo.CurrentCulture, Get("RecoveryChangesOne"), arg0, arg1);

    /// <summary>{0} changes were made and never saved, last on {1}.</summary>
    public static string RecoveryChangesOther(object? arg0, object? arg1) => string.Format(CultureInfo.CurrentCulture, Get("RecoveryChangesOther"), arg0, arg1);

    /// <summary>Restoring reopens the document and puts them back; nothing is written to the file until you save.</summary>
    public static string RecoveryExplanation => Get("RecoveryExplanation");

    /// <summary>Discard them</summary>
    public static string DiscardThem => Get("DiscardThem");

    /// <summary>Decide later</summary>
    public static string DecideLater => Get("DecideLater");

    /// <summary>Restore</summary>
    public static string Restore => Get("Restore");

    /// <summary>Password needed</summary>
    public static string PasswordNeeded => Get("PasswordNeeded");

    /// <summary>Password</summary>
    public static string Password => Get("Password");

    /// <summary>Cancel</summary>
    public static string Cancel => Get("Cancel");

    /// <summary>"{0}" is password-protected. Enter its password to open it.</summary>
    public static string PasswordPrompt(object? arg0) => string.Format(CultureInfo.CurrentCulture, Get("PasswordPrompt"), arg0);

    /// <summary>That password did not open "{0}". Try again?</summary>
    public static string PasswordRetryPrompt(object? arg0) => string.Format(CultureInfo.CurrentCulture, Get("PasswordRetryPrompt"), arg0);

    /// <summary>Add a signature</summary>
    public static string AddASignature => Get("AddASignature");

    /// <summary>Sign in the box below, the way you would on paper.</summary>
    public static string SignInTheBox => Get("SignInTheBox");

    /// <summary>Clear</summary>
    public static string Clear => Get("Clear");

    /// <summary>Name</summary>
    public static string Name => Get("Name");

    /// <summary>e.g. Dave</summary>
    public static string NameExample => Get("NameExample");
}
