// <auto-generated>
//   Generated by tools/gen_strings.py from src/MegaPDF.App/Strings/en-US/Resources.resw.
//   Do not edit: change the catalogue and re-run the script.
// </auto-generated>
#nullable enable
using System.Globalization;

namespace MegaPDF.App;

/// <summary>
/// Typed access to the English catalogue's keys (#91). Every user-facing string
/// in code goes through here, so a missing key is a compile error rather than a
/// runtime blank.
/// </summary>
public static partial class Strings
{
    private static string Get(string key) => AppLanguage.GetString(key);

    /// <summary>A lightweight PDF editor — open, fix, save, done.</summary>
    public static string AppDescription => Get("AppDescription");

    /// <summary>PDF document</summary>
    public static string PdfFileTypeName => Get("PdfFileTypeName");

    /// <summary>Page {0}</summary>
    public static string PageN(object? arg0) => string.Format(CultureInfo.CurrentCulture, Get("PageN"), arg0);

    /// <summary>Page {0} of {1}</summary>
    public static string PageOf(object? arg0, object? arg1) => string.Format(CultureInfo.CurrentCulture, Get("PageOf"), arg0, arg1);

    /// <summary>Save</summary>
    public static string Save => Get("Save");

    /// <summary>Save ●</summary>
    public static string SaveWithDot => Get("SaveWithDot");

    /// <summary>No results</summary>
    public static string NoResults => Get("NoResults");

    /// <summary>{0} of {1}</summary>
    public static string MatchOf(object? arg0, object? arg1) => string.Format(CultureInfo.CurrentCulture, Get("MatchOf"), arg0, arg1);

    /// <summary>Click on the page to place “{0}”</summary>
    public static string PlaceSignatureHint(object? arg0) => string.Format(CultureInfo.CurrentCulture, Get("PlaceSignatureHint"), arg0);

    /// <summary>Drag across the area you want to cover — Esc cancels</summary>
    public static string WhiteoutHint => Get("WhiteoutHint");

    /// <summary>Click where the new text should go — Esc cancels</summary>
    public static string TextBoxHint => Get("TextBoxHint");

    /// <summary>Couldn't open that file</summary>
    public static string CouldNotOpenTitle => Get("CouldNotOpenTitle");

    /// <summary>Couldn't add that signature</summary>
    public static string CouldNotAddSignatureTitle => Get("CouldNotAddSignatureTitle");

    /// <summary>Couldn't place the signature</summary>
    public static string CouldNotPlaceSignatureTitle => Get("CouldNotPlaceSignatureTitle");

    /// <summary>Can't edit this text</summary>
    public static string CannotEditTextTitle => Get("CannotEditTextTitle");

    /// <summary>Couldn't save</summary>
    public static string CouldNotSaveTitle => Get("CouldNotSaveTitle");

    /// <summary>Try "Save As" to save a copy instead.</summary>
    public static string TrySaveAsHint => Get("TrySaveAsHint");

    /// <summary>PDF document</summary>
    public static string PdfDocumentFilter => Get("PdfDocumentFilter");

    /// <summary>{0} - edited</summary>
    public static string EditedFileName(object? arg0) => string.Format(CultureInfo.CurrentCulture, Get("EditedFileName"), arg0);

    /// <summary>{0} - smaller</summary>
    public static string SmallerFileName(object? arg0) => string.Format(CultureInfo.CurrentCulture, Get("SmallerFileName"), arg0);

    /// <summary>Save first</summary>
    public static string SaveFirstTitle => Get("SaveFirstTitle");

    /// <summary>Save your changes, then shrink the saved file.</summary>
    public static string SaveFirstBody => Get("SaveFirstBody");

    /// <summary>Couldn't shrink</summary>
    public static string CouldNotShrinkTitle => Get("CouldNotShrinkTitle");

    /// <summary>Nothing to shrink</summary>
    public static string NothingToShrinkTitle => Get("NothingToShrinkTitle");

    /// <summary>The pictures in this document are already small.</summary>
    public static string NothingToShrinkBody => Get("NothingToShrinkBody");

    /// <summary>Smaller copy saved</summary>
    public static string SmallerCopySavedTitle => Get("SmallerCopySavedTitle");

    /// <summary>Was {0:F1} MB, now {1:F1} MB.  Saved as {2} — ready to email.</summary>
    public static string SmallerCopySavedBody(object? arg0, object? arg1, object? arg2) => string.Format(CultureInfo.CurrentCulture, Get("SmallerCopySavedBody"), arg0, arg1, arg2);

    /// <summary>Password</summary>
    public static string PasswordPlaceholder => Get("PasswordPlaceholder");

    /// <summary>That password wasn't right — try again.</summary>
    public static string PasswordWrong => Get("PasswordWrong");

    /// <summary>“{0}” is protected. Enter its password to open it.</summary>
    public static string PasswordPrompt(object? arg0) => string.Format(CultureInfo.CurrentCulture, Get("PasswordPrompt"), arg0);

    /// <summary>Password required</summary>
    public static string PasswordRequiredTitle => Get("PasswordRequiredTitle");

    /// <summary>Open</summary>
    public static string Open => Get("Open");

    /// <summary>Cancel</summary>
    public static string Cancel => Get("Cancel");

    /// <summary>OK</summary>
    public static string OK => Get("OK");

    /// <summary>Text size</summary>
    public static string TextSizeName => Get("TextSizeName");

    /// <summary>Text font</summary>
    public static string TextFontName => Get("TextFontName");

    /// <summary>Edit text</summary>
    public static string EditTextName => Get("EditTextName");

    /// <summary>Restore unsaved changes?</summary>
    public static string RestoreTitle => Get("RestoreTitle");

    /// <summary>{0} closed unexpectedly with unsaved changes to {1}.</summary>
    public static string RestoreBody(object? arg0, object? arg1) => string.Format(CultureInfo.CurrentCulture, Get("RestoreBody"), arg0, arg1);

    /// <summary>Restore</summary>
    public static string Restore => Get("Restore");

    /// <summary>Discard</summary>
    public static string Discard => Get("Discard");

    /// <summary>Save changes to {0}?</summary>
    public static string SaveChangesTitle(object? arg0) => string.Format(CultureInfo.CurrentCulture, Get("SaveChangesTitle"), arg0);

    /// <summary>Your changes will be lost if you don't save them.</summary>
    public static string SaveChangesBody => Get("SaveChangesBody");

    /// <summary>Don't save</summary>
    public static string DontSave => Get("DontSave");

    /// <summary>MegaPDF {0}</summary>
    public static string AboutVersion(object? arg0) => string.Format(CultureInfo.CurrentCulture, Get("AboutVersion"), arg0);

    /// <summary>The third-party notices file could not be loaded.</summary>
    public static string NoticesLoadFailed => Get("NoticesLoadFailed");

    /// <summary>Third-party notices text</summary>
    public static string NoticesTextName => Get("NoticesTextName");

    /// <summary>Third-party notices</summary>
    public static string NoticesTitle => Get("NoticesTitle");

    /// <summary>Close</summary>
    public static string Close => Get("Close");

    /// <summary>Your name</summary>
    public static string YourNamePlaceholder => Get("YourNamePlaceholder");

    /// <summary>Type your signature</summary>
    public static string TypeSignatureTitle => Get("TypeSignatureTitle");

    /// <summary>Add</summary>
    public static string Add => Get("Add");

    /// <summary>Signature name</summary>
    public static string SignatureNamePlaceholder => Get("SignatureNamePlaceholder");

    /// <summary>My signature</summary>
    public static string MySignature => Get("MySignature");

    /// <summary>Clear</summary>
    public static string Clear => Get("Clear");

    /// <summary>Draw with your mouse, finger, or pen.</summary>
    public static string DrawHint => Get("DrawHint");

    /// <summary>Draw your signature</summary>
    public static string DrawSignatureTitle => Get("DrawSignatureTitle");

    /// <summary>The file could not be read.</summary>
    public static string ErrorFileUnreadable => Get("ErrorFileUnreadable");

    /// <summary>That file is not a PDF.</summary>
    public static string ErrorNotAPdf => Get("ErrorNotAPdf");

    /// <summary>The file is password-protected.</summary>
    public static string ErrorPasswordProtected => Get("ErrorPasswordProtected");

    /// <summary>The file could not be opened (error {0}).</summary>
    public static string ErrorCouldNotOpen(object? arg0) => string.Format(CultureInfo.CurrentCulture, Get("ErrorCouldNotOpen"), arg0);

    /// <summary>The saved document could not be read back, so the original was left untouched.</summary>
    public static string ErrorSavedCopyUnreadable => Get("ErrorSavedCopyUnreadable");

    /// <summary>No available font can write that text.</summary>
    public static string ErrorNoUsableFont => Get("ErrorNoUsableFont");

    /// <summary>That text is part of a scanned image, so it cannot be edited. Cover it with whiteout and add new text instead.</summary>
    public static string ErrorNotExtractable => Get("ErrorNotExtractable");

    /// <summary>Something went wrong.</summary>
    public static string ErrorGeneric => Get("ErrorGeneric");
}
