// <auto-generated>
//   Generated by tools/gen_strings.py from src/MegaPDF.App/Strings/en-US/Resources.resw.
//   Do not edit: change the catalogue and re-run the script.
// </auto-generated>
#nullable enable
using System.Globalization;

namespace MegaPDF.App;

/// <summary>
/// Typed access to the English catalogue's keys (#91). Every user-facing string
/// in code goes through here, so a missing key is a compile error rather than a
/// runtime blank.
/// </summary>
public static partial class Strings
{
    private static string Get(string key) => AppLanguage.GetString(key);

    /// <summary>A lightweight PDF editor — open, fix, save, done.</summary>
    public static string AppDescription => Get("AppDescription");

    /// <summary>PDF document</summary>
    public static string PdfFileTypeName => Get("PdfFileTypeName");

    /// <summary>Page {0}</summary>
    public static string PageN(object? arg0) => string.Format(CultureInfo.CurrentCulture, Get("PageN"), arg0);

    /// <summary>Page {0} of {1}</summary>
    public static string PageOf(object? arg0, object? arg1) => string.Format(CultureInfo.CurrentCulture, Get("PageOf"), arg0, arg1);

    /// <summary>Save</summary>
    public static string Save => Get("Save");

    /// <summary>Save ●</summary>
    public static string SaveWithDot => Get("SaveWithDot");

    /// <summary>No results</summary>
    public static string NoResults => Get("NoResults");

    /// <summary>{0} of {1}</summary>
    public static string MatchOf(object? arg0, object? arg1) => string.Format(CultureInfo.CurrentCulture, Get("MatchOf"), arg0, arg1);

    /// <summary>{0} off</summary>
    public static string ToolOffNotice(object? arg0) => string.Format(CultureInfo.CurrentCulture, Get("ToolOffNotice"), arg0);

    /// <summary>Click on the page to place “{0}”</summary>
    public static string PlaceSignatureHint(object? arg0) => string.Format(CultureInfo.CurrentCulture, Get("PlaceSignatureHint"), arg0);

    /// <summary>Drag across the area you want to cover — Esc cancels. Covering doesn't remove; Redact does</summary>
    public static string WhiteoutHint => Get("WhiteoutHint");

    /// <summary>Click where the new text should go — Esc cancels</summary>
    public static string TextBoxHint => Get("TextBoxHint");

    /// <summary>Couldn't open that file</summary>
    public static string CouldNotOpenTitle => Get("CouldNotOpenTitle");

    /// <summary>This page couldn't be displayed.</summary>
    public static string PageRenderFailed => Get("PageRenderFailed");

    /// <summary>Couldn't add that signature</summary>
    public static string CouldNotAddSignatureTitle => Get("CouldNotAddSignatureTitle");

    /// <summary>Couldn't place the signature</summary>
    public static string CouldNotPlaceSignatureTitle => Get("CouldNotPlaceSignatureTitle");

    /// <summary>Can't edit this text</summary>
    public static string CannotEditTextTitle => Get("CannotEditTextTitle");

    /// <summary>Couldn't save</summary>
    public static string CouldNotSaveTitle => Get("CouldNotSaveTitle");

    /// <summary>Try "Save As" to save a copy instead.</summary>
    public static string TrySaveAsHint => Get("TrySaveAsHint");

    /// <summary>PDF document</summary>
    public static string PdfDocumentFilter => Get("PdfDocumentFilter");

    /// <summary>Markdown document</summary>
    public static string MarkdownDocumentFilter => Get("MarkdownDocumentFilter");

    /// <summary>Couldn't export</summary>
    public static string CouldNotExportTitle => Get("CouldNotExportTitle");

    /// <summary>{0} - edited</summary>
    public static string EditedFileName(object? arg0) => string.Format(CultureInfo.CurrentCulture, Get("EditedFileName"), arg0);

    /// <summary>{0} - smaller</summary>
    public static string SmallerFileName(object? arg0) => string.Format(CultureInfo.CurrentCulture, Get("SmallerFileName"), arg0);

    /// <summary>Save first</summary>
    public static string SaveFirstTitle => Get("SaveFirstTitle");

    /// <summary>Save your changes, then shrink the saved file.</summary>
    public static string SaveFirstBody => Get("SaveFirstBody");

    /// <summary>Couldn't shrink</summary>
    public static string CouldNotShrinkTitle => Get("CouldNotShrinkTitle");

    /// <summary>Nothing to shrink</summary>
    public static string NothingToShrinkTitle => Get("NothingToShrinkTitle");

    /// <summary>The pictures in this document are already small.</summary>
    public static string NothingToShrinkBody => Get("NothingToShrinkBody");

    /// <summary>Smaller copy saved</summary>
    public static string SmallerCopySavedTitle => Get("SmallerCopySavedTitle");

    /// <summary>Was {0:F1} MB, now {1:F1} MB.  Saved as {2} — ready to email.</summary>
    public static string SmallerCopySavedBody(object? arg0, object? arg1, object? arg2) => string.Format(CultureInfo.CurrentCulture, Get("SmallerCopySavedBody"), arg0, arg1, arg2);

    /// <summary>Password</summary>
    public static string PasswordPlaceholder => Get("PasswordPlaceholder");

    /// <summary>That password wasn't right — try again.</summary>
    public static string PasswordWrong => Get("PasswordWrong");

    /// <summary>“{0}” is protected. Enter its password to open it.</summary>
    public static string PasswordPrompt(object? arg0) => string.Format(CultureInfo.CurrentCulture, Get("PasswordPrompt"), arg0);

    /// <summary>Password required</summary>
    public static string PasswordRequiredTitle => Get("PasswordRequiredTitle");

    /// <summary>Open</summary>
    public static string Open => Get("Open");

    /// <summary>Cancel</summary>
    public static string Cancel => Get("Cancel");

    /// <summary>OK</summary>
    public static string OK => Get("OK");

    /// <summary>Unlock document</summary>
    public static string UnlockTitle => Get("UnlockTitle");

    /// <summary>The owner of “{0}” restricted what can be done with it. Enter the owner password to use every tool.</summary>
    public static string UnlockPrompt(object? arg0) => string.Format(CultureInfo.CurrentCulture, Get("UnlockPrompt"), arg0);

    /// <summary>That password didn't unlock the document — try again.</summary>
    public static string UnlockWrong => Get("UnlockWrong");

    /// <summary>Unlock</summary>
    public static string Unlock => Get("Unlock");

    /// <summary>Set password</summary>
    public static string SetPasswordTitle => Get("SetPasswordTitle");

    /// <summary>Set password</summary>
    public static string SetPasswordButton => Get("SetPasswordButton");

    /// <summary>Change password</summary>
    public static string ChangePasswordTitle => Get("ChangePasswordTitle");

    /// <summary>Change password</summary>
    public static string ChangePasswordButton => Get("ChangePasswordButton");

    /// <summary>Anyone who opens “{0}” will need this password. MegaPDF can't recover it if it's forgotten.</summary>
    public static string SetPasswordBody(object? arg0) => string.Format(CultureInfo.CurrentCulture, Get("SetPasswordBody"), arg0);

    /// <summary>New password</summary>
    public static string NewPasswordPlaceholder => Get("NewPasswordPlaceholder");

    /// <summary>Confirm password</summary>
    public static string ConfirmPasswordPlaceholder => Get("ConfirmPasswordPlaceholder");

    /// <summary>Enter a password.</summary>
    public static string PasswordEmpty => Get("PasswordEmpty");

    /// <summary>The passwords don't match.</summary>
    public static string PasswordsDontMatch => Get("PasswordsDontMatch");

    /// <summary>Document password</summary>
    public static string DocumentPasswordTitle => Get("DocumentPasswordTitle");

    /// <summary>“{0}” is protected by a password. You can change it or remove it.</summary>
    public static string ProtectedBody(object? arg0) => string.Format(CultureInfo.CurrentCulture, Get("ProtectedBody"), arg0);

    /// <summary>Change password…</summary>
    public static string ChangePasswordEllipsis => Get("ChangePasswordEllipsis");

    /// <summary>Remove password</summary>
    public static string RemovePassword => Get("RemovePassword");

    /// <summary>Password set.</summary>
    public static string PasswordSetNotice => Get("PasswordSetNotice");

    /// <summary>Password changed.</summary>
    public static string PasswordChangedNotice => Get("PasswordChangedNotice");

    /// <summary>Password removed.</summary>
    public static string PasswordRemovedNotice => Get("PasswordRemovedNotice");

    /// <summary>Couldn't change the password</summary>
    public static string CouldNotChangeSecurityTitle => Get("CouldNotChangeSecurityTitle");

    /// <summary>Text size</summary>
    public static string TextSizeName => Get("TextSizeName");

    /// <summary>Text font</summary>
    public static string TextFontName => Get("TextFontName");

    /// <summary>Edit text</summary>
    public static string EditTextName => Get("EditTextName");

    /// <summary>Restore unsaved changes?</summary>
    public static string RestoreTitle => Get("RestoreTitle");

    /// <summary>{0} closed unexpectedly with unsaved changes to {1}.</summary>
    public static string RestoreBody(object? arg0, object? arg1) => string.Format(CultureInfo.CurrentCulture, Get("RestoreBody"), arg0, arg1);

    /// <summary>Restore</summary>
    public static string Restore => Get("Restore");

    /// <summary>Discard</summary>
    public static string Discard => Get("Discard");

    /// <summary>Save changes to {0}?</summary>
    public static string SaveChangesTitle(object? arg0) => string.Format(CultureInfo.CurrentCulture, Get("SaveChangesTitle"), arg0);

    /// <summary>Your changes will be lost if you don't save them.</summary>
    public static string SaveChangesBody => Get("SaveChangesBody");

    /// <summary>Don't save</summary>
    public static string DontSave => Get("DontSave");

    /// <summary>MegaPDF {0}</summary>
    public static string AboutVersion(object? arg0) => string.Format(CultureInfo.CurrentCulture, Get("AboutVersion"), arg0);

    /// <summary>The third-party notices file could not be loaded.</summary>
    public static string NoticesLoadFailed => Get("NoticesLoadFailed");

    /// <summary>Third-party notices text</summary>
    public static string NoticesTextName => Get("NoticesTextName");

    /// <summary>Third-party notices</summary>
    public static string NoticesTitle => Get("NoticesTitle");

    /// <summary>Close</summary>
    public static string Close => Get("Close");

    /// <summary>Your name</summary>
    public static string YourNamePlaceholder => Get("YourNamePlaceholder");

    /// <summary>Type your signature</summary>
    public static string TypeSignatureTitle => Get("TypeSignatureTitle");

    /// <summary>Add</summary>
    public static string Add => Get("Add");

    /// <summary>Signature name</summary>
    public static string SignatureNamePlaceholder => Get("SignatureNamePlaceholder");

    /// <summary>My signature</summary>
    public static string MySignature => Get("MySignature");

    /// <summary>Clear</summary>
    public static string Clear => Get("Clear");

    /// <summary>Draw with your mouse, finger, or pen.</summary>
    public static string DrawHint => Get("DrawHint");

    /// <summary>Draw your signature</summary>
    public static string DrawSignatureTitle => Get("DrawSignatureTitle");

    /// <summary>The file could not be read.</summary>
    public static string ErrorFileUnreadable => Get("ErrorFileUnreadable");

    /// <summary>This file is too large for MegaPDF to open.</summary>
    public static string ErrorFileTooLarge => Get("ErrorFileTooLarge");

    /// <summary>That file is not a PDF.</summary>
    public static string ErrorNotAPdf => Get("ErrorNotAPdf");

    /// <summary>The file is password-protected.</summary>
    public static string ErrorPasswordProtected => Get("ErrorPasswordProtected");

    /// <summary>The file could not be opened (error {0}).</summary>
    public static string ErrorCouldNotOpen(object? arg0) => string.Format(CultureInfo.CurrentCulture, Get("ErrorCouldNotOpen"), arg0);

    /// <summary>The saved document could not be read back, so the original was left untouched.</summary>
    public static string ErrorSavedCopyUnreadable => Get("ErrorSavedCopyUnreadable");

    /// <summary>No available font can write that text.</summary>
    public static string ErrorNoUsableFont => Get("ErrorNoUsableFont");

    /// <summary>That text is part of a scanned image, so it cannot be edited. Cover it with whiteout and add new text instead.</summary>
    public static string ErrorNotExtractable => Get("ErrorNotExtractable");

    /// <summary>This page's text can't be changed without disturbing its layout: rewriting it would shift the spacing of other text. Cover it with whiteout and add new text instead.</summary>
    public static string ErrorLayoutWouldChange => Get("ErrorLayoutWouldChange");

    /// <summary>This line can't be changed without making other parts of the page look different. Cover it with whiteout and add new text instead.</summary>
    public static string ErrorLayoutRenderWouldChange => Get("ErrorLayoutRenderWouldChange");

    /// <summary>This line can't be changed without moving text elsewhere on the page. Cover it with whiteout and add new text instead.</summary>
    public static string ErrorLayoutTextWouldMove => Get("ErrorLayoutTextWouldMove");

    /// <summary>This PDF uses a kind of protection MegaPDF can't open.</summary>
    public static string ErrorUnsupportedSecurity => Get("ErrorUnsupportedSecurity");

    /// <summary>The document's owner doesn't allow this. Unlock it with the owner password first.</summary>
    public static string ErrorRestricted => Get("ErrorRestricted");

    /// <summary>Something went wrong.</summary>
    public static string ErrorGeneric => Get("ErrorGeneric");

    /// <summary>{0}, signature</summary>
    public static string SignatureCardName(object? arg0) => string.Format(CultureInfo.CurrentCulture, Get("SignatureCardName"), arg0);

    /// <summary>Rename</summary>
    public static string Rename => Get("Rename");

    /// <summary>Delete</summary>
    public static string Delete => Get("Delete");

    /// <summary>Rename signature</summary>
    public static string RenameSignatureTitle => Get("RenameSignatureTitle");

    /// <summary>Delete {0}?</summary>
    public static string DeleteSignatureTitle(object? arg0) => string.Format(CultureInfo.CurrentCulture, Get("DeleteSignatureTitle"), arg0);

    /// <summary>This cannot be undone.</summary>
    public static string DeleteSignatureBody => Get("DeleteSignatureBody");

    /// <summary>Couldn't rename that signature</summary>
    public static string CouldNotRenameSignatureTitle => Get("CouldNotRenameSignatureTitle");

    /// <summary>Nothing on this document can be changed from the keyboard.</summary>
    public static string NothingKeyboardEditable => Get("NothingKeyboardEditable");

    /// <summary>Checkbox, ticked</summary>
    public static string RegionCheckboxTicked => Get("RegionCheckboxTicked");

    /// <summary>Checkbox, not ticked</summary>
    public static string RegionCheckboxNotTicked => Get("RegionCheckboxNotTicked");

    /// <summary>Box to tick</summary>
    public static string RegionBoxToTick => Get("RegionBoxToTick");

    /// <summary>Box, ticked</summary>
    public static string RegionBoxTicked => Get("RegionBoxTicked");

    /// <summary>Form field</summary>
    public static string RegionFormField => Get("RegionFormField");

    /// <summary>Text, editable</summary>
    public static string RegionTextEditable => Get("RegionTextEditable");

    /// <summary>Added text</summary>
    public static string RegionAddedText => Get("RegionAddedText");

    /// <summary>Signature or tick mark</summary>
    public static string RegionSignatureOrMark => Get("RegionSignatureOrMark");

    /// <summary>Cover</summary>
    public static string RegionCover => Get("RegionCover");

    /// <summary>Page</summary>
    public static string RegionPage => Get("RegionPage");

    /// <summary>Page {0}, {1}</summary>
    public static string PageRegionDescription(object? arg0, object? arg1) => string.Format(CultureInfo.CurrentCulture, Get("PageRegionDescription"), arg0, arg1);

    /// <summary>page region</summary>
    public static string PageRegionControlType => Get("PageRegionControlType");

    /// <summary>Signature selected. Arrow keys move it, Delete removes it, Esc lets it go.</summary>
    public static string SignatureSelectedKeyHint => Get("SignatureSelectedKeyHint");

    /// <summary>Text selected. Arrow keys move it, Enter edits it, Delete removes it, Esc lets it go.</summary>
    public static string TextBoxSelectedKeyHint => Get("TextBoxSelectedKeyHint");

    /// <summary>Cover selected. Delete removes it, Esc lets it go.</summary>
    public static string CoverSelectedKeyHint => Get("CoverSelectedKeyHint");

    /// <summary>Tab to where the signature goes on the page, then press Enter.</summary>
    public static string PlaceSignatureKeyHint => Get("PlaceSignatureKeyHint");

    /// <summary>Change this page?</summary>
    public static string PageRewriteWarningTitle => Get("PageRewriteWarningTitle");

    /// <summary>Changing this page may slightly alter parts of it you haven't touched.</summary>
    public static string PageRewriteWarning => Get("PageRewriteWarning");

    /// <summary>Continue</summary>
    public static string Continue => Get("Continue");

    /// <summary>Open</summary>
    public static string ToolbarOpen => Get("ToolbarOpen");

    /// <summary>Open a PDF (Ctrl+O)</summary>
    public static string ToolbarOpenTip => Get("ToolbarOpenTip");

    /// <summary>Save (Ctrl+S)</summary>
    public static string ToolbarSaveTip => Get("ToolbarSaveTip");

    /// <summary>Save As</summary>
    public static string ToolbarSaveAs => Get("ToolbarSaveAs");

    /// <summary>Save a copy (Ctrl+Shift+S)</summary>
    public static string ToolbarSaveAsTip => Get("ToolbarSaveAsTip");

    /// <summary>Password…</summary>
    public static string ToolbarPassword => Get("ToolbarPassword");

    /// <summary>Password</summary>
    public static string ToolbarPasswordName => Get("ToolbarPasswordName");

    /// <summary>Set, change or remove the document's password</summary>
    public static string ToolbarPasswordTip => Get("ToolbarPasswordTip");

    /// <summary>Shrink</summary>
    public static string ToolbarShrink => Get("ToolbarShrink");

    /// <summary>Shrink for email</summary>
    public static string ToolbarShrinkName => Get("ToolbarShrinkName");

    /// <summary>Save a smaller copy for email</summary>
    public static string ToolbarShrinkTip => Get("ToolbarShrinkTip");

    /// <summary>Print</summary>
    public static string ToolbarPrint => Get("ToolbarPrint");

    /// <summary>Print (Ctrl+P)</summary>
    public static string ToolbarPrintTip => Get("ToolbarPrintTip");

    /// <summary>Undo</summary>
    public static string ToolbarUndo => Get("ToolbarUndo");

    /// <summary>Undo (Ctrl+Z)</summary>
    public static string ToolbarUndoTip => Get("ToolbarUndoTip");

    /// <summary>Redo</summary>
    public static string ToolbarRedo => Get("ToolbarRedo");

    /// <summary>Redo (Ctrl+Y)</summary>
    public static string ToolbarRedoTip => Get("ToolbarRedoTip");

    /// <summary>Signatures</summary>
    public static string ToolbarSignatures => Get("ToolbarSignatures");

    /// <summary>Your signatures</summary>
    public static string ToolbarSignaturesTip => Get("ToolbarSignaturesTip");

    /// <summary>Whiteout</summary>
    public static string ToolbarWhiteout => Get("ToolbarWhiteout");

    /// <summary>Cover an area — this doesn't remove what's under it</summary>
    public static string ToolbarWhiteoutTip => Get("ToolbarWhiteoutTip");

    /// <summary>Add text</summary>
    public static string ToolbarAddText => Get("ToolbarAddText");

    /// <summary>Add new text anywhere</summary>
    public static string ToolbarAddTextTip => Get("ToolbarAddTextTip");

    /// <summary>Find</summary>
    public static string ToolbarFind => Get("ToolbarFind");

    /// <summary>Find in document (Ctrl+F)</summary>
    public static string ToolbarFindTip => Get("ToolbarFindTip");

    /// <summary>Zoom out</summary>
    public static string ToolbarZoomOut => Get("ToolbarZoomOut");

    /// <summary>Zoom out (Ctrl+Minus)</summary>
    public static string ToolbarZoomOutTip => Get("ToolbarZoomOutTip");

    /// <summary>Zoom in</summary>
    public static string ToolbarZoomIn => Get("ToolbarZoomIn");

    /// <summary>Zoom in (Ctrl+Plus)</summary>
    public static string ToolbarZoomInTip => Get("ToolbarZoomInTip");

    /// <summary>Zoom level</summary>
    public static string ToolbarZoomLevel => Get("ToolbarZoomLevel");

    /// <summary>Actual size</summary>
    public static string ToolbarActualSize => Get("ToolbarActualSize");

    /// <summary>Fit width</summary>
    public static string ToolbarFitWidth => Get("ToolbarFitWidth");

    /// <summary>Fit page</summary>
    public static string ToolbarFitPage => Get("ToolbarFitPage");

    /// <summary>Settings</summary>
    public static string ToolbarSettings => Get("ToolbarSettings");

    /// <summary>{0}%</summary>
    public static string ZoomPercent(object? arg0) => string.Format(CultureInfo.CurrentCulture, Get("ZoomPercent"), arg0);

    /// <summary>Opening…</summary>
    public static string BusyOpening => Get("BusyOpening");

    /// <summary>Saving…</summary>
    public static string BusySaving => Get("BusySaving");

    /// <summary>Checking the saved file…</summary>
    public static string BusyCheckingSavedFile => Get("BusyCheckingSavedFile");

    /// <summary>Exporting…</summary>
    public static string BusyExportingMarkdown => Get("BusyExportingMarkdown");

    /// <summary>Checking this page…</summary>
    public static string BusyCheckingPage => Get("BusyCheckingPage");

    /// <summary>Applying…</summary>
    public static string BusyApplying => Get("BusyApplying");

    /// <summary>Searching…</summary>
    public static string BusySearching => Get("BusySearching");

    /// <summary>Making a smaller copy…</summary>
    public static string BusyShrinking => Get("BusyShrinking");

    /// <summary>Preparing to print…</summary>
    public static string BusyPrinting => Get("BusyPrinting");

    /// <summary>Restoring your edits…</summary>
    public static string BusyRestoring => Get("BusyRestoring");

    /// <summary>Couldn't print</summary>
    public static string CouldNotPrintTitle => Get("CouldNotPrintTitle");

    /// <summary>Couldn't make that change</summary>
    public static string CouldNotEditTitle => Get("CouldNotEditTitle");

    /// <summary>Couldn't restore your edits</summary>
    public static string CouldNotRestoreTitle => Get("CouldNotRestoreTitle");

    /// <summary>Not found</summary>
    public static string RecentNotFound => Get("RecentNotFound");

    /// <summary>{0}, in {1}</summary>
    public static string RecentItemName(object? arg0, object? arg1) => string.Format(CultureInfo.CurrentCulture, Get("RecentItemName"), arg0, arg1);

    /// <summary>{0}, in {1}, not found</summary>
    public static string RecentItemMissingName(object? arg0, object? arg1) => string.Format(CultureInfo.CurrentCulture, Get("RecentItemMissingName"), arg0, arg1);

    /// <summary>Can't find this file</summary>
    public static string RecentMissingTitle => Get("RecentMissingTitle");

    /// <summary>“{0}” is no longer in {1}. It may have been moved, renamed or deleted.</summary>
    public static string RecentMissingBody(object? arg0, object? arg1) => string.Format(CultureInfo.CurrentCulture, Get("RecentMissingBody"), arg0, arg1);

    /// <summary>Remove from Recent</summary>
    public static string RemoveFromRecent => Get("RemoveFromRecent");

    /// <summary>Draw a signature</summary>
    public static string DrawSignatureName => Get("DrawSignatureName");

    /// <summary>Type a signature</summary>
    public static string TypeSignatureName => Get("TypeSignatureName");

    /// <summary>Add a signature from a photo</summary>
    public static string AddFromImageName => Get("AddFromImageName");

    /// <summary>Redact</summary>
    public static string ToolbarRedact => Get("ToolbarRedact");

    /// <summary>Remove content from the file</summary>
    public static string ToolbarRedactTip => Get("ToolbarRedactTip");

    /// <summary>Drag across what you want removed, select text, or press Enter on the focused item — Esc cancels</summary>
    public static string RedactHint => Get("RedactHint");

    /// <summary>Marked for redaction</summary>
    public static string RedactMarkName => Get("RedactMarkName");

    /// <summary>{0} areas marked for redaction</summary>
    public static string RedactMarkCount(object? arg0) => string.Format(CultureInfo.CurrentCulture, Get("RedactMarkCount"), arg0);

    /// <summary>1 area marked for redaction</summary>
    public static string RedactMarkCountOne => Get("RedactMarkCountOne");

    /// <summary>Marked for redaction.</summary>
    public static string RedactMarkPlaced => Get("RedactMarkPlaced");

    /// <summary>Mark removed.</summary>
    public static string RedactMarkRemoved => Get("RedactMarkRemoved");

    /// <summary>All marks cleared. Undo puts them back.</summary>
    public static string RedactMarksCleared => Get("RedactMarksCleared");

    /// <summary>Mark selected. Arrow keys move it, Delete removes it, Esc lets it go.</summary>
    public static string RedactMarkSelectedKeyHint => Get("RedactMarkSelectedKeyHint");

    /// <summary>Clear all marks</summary>
    public static string ToolbarClearMarks => Get("ToolbarClearMarks");

    /// <summary>Drop every redaction mark on the document</summary>
    public static string ToolbarClearMarksTip => Get("ToolbarClearMarksTip");

    /// <summary>Remove the marked content?</summary>
    public static string RedactConfirmTitle => Get("RedactConfirmTitle");

    /// <summary>Redaction permanently removes the marked content. This can't be undone after saving.</summary>
    public static string RedactConfirmBody => Get("RedactConfirmBody");

    /// <summary>Save as a copy</summary>
    public static string RedactSaveCopy => Get("RedactSaveCopy");

    /// <summary>Overwrite the original</summary>
    public static string RedactOverwrite => Get("RedactOverwrite");

    /// <summary>-redacted</summary>
    public static string RedactedFileSuffix => Get("RedactedFileSuffix");

    /// <summary>1 area redacted: {0}</summary>
    public static string RedactSummaryOne(object? arg0) => string.Format(CultureInfo.CurrentCulture, Get("RedactSummaryOne"), arg0);

    /// <summary>{0} areas redacted: {1}</summary>
    public static string RedactSummaryMany(object? arg0, object? arg1) => string.Format(CultureInfo.CurrentCulture, Get("RedactSummaryMany"), arg0, arg1);

    /// <summary>{0} characters</summary>
    public static string RedactedCharacters(object? arg0) => string.Format(CultureInfo.CurrentCulture, Get("RedactedCharacters"), arg0);

    /// <summary>1 character</summary>
    public static string RedactedCharactersOne => Get("RedactedCharactersOne");

    /// <summary>{0} images</summary>
    public static string RedactedImages(object? arg0) => string.Format(CultureInfo.CurrentCulture, Get("RedactedImages"), arg0);

    /// <summary>1 image</summary>
    public static string RedactedImagesOne => Get("RedactedImagesOne");

    /// <summary>{0} form fields</summary>
    public static string RedactedFormFields(object? arg0) => string.Format(CultureInfo.CurrentCulture, Get("RedactedFormFields"), arg0);

    /// <summary>1 form field</summary>
    public static string RedactedFormFieldsOne => Get("RedactedFormFieldsOne");

    /// <summary>{0} annotations</summary>
    public static string RedactedAnnotations(object? arg0) => string.Format(CultureInfo.CurrentCulture, Get("RedactedAnnotations"), arg0);

    /// <summary>1 annotation</summary>
    public static string RedactedAnnotationsOne => Get("RedactedAnnotationsOne");

    /// <summary>nothing</summary>
    public static string RedactedNothing => Get("RedactedNothing");

    /// <summary>Nothing was removed</summary>
    public static string RedactRefusedTitle => Get("RedactRefusedTitle");

    /// <summary>MegaPDF couldn't remove everything you marked on page {0}, so it removed nothing and left the file as it was.</summary>
    public static string RedactRefusedBody(object? arg0) => string.Format(CultureInfo.CurrentCulture, Get("RedactRefusedBody"), arg0);

    /// <summary>The text there is in a font MegaPDF can't redraw around your marks.</summary>
    public static string RedactRefusedFont => Get("RedactRefusedFont");

    /// <summary>Part of that area is drawn from a shared block MegaPDF can't take apart safely.</summary>
    public static string RedactRefusedShared => Get("RedactRefusedShared");

    /// <summary>Removing it would change the page outside the areas you marked.</summary>
    public static string RedactRefusedLayout => Get("RedactRefusedLayout");

    /// <summary>MegaPDF couldn't take that content apart safely.</summary>
    public static string RedactRefusedOther => Get("RedactRefusedOther");

    /// <summary>This document doesn't allow changes, so it can't be redacted.</summary>
    public static string RedactNeedsPermission => Get("RedactNeedsPermission");

    /// <summary>The redaction couldn't be finished, and this file can no longer be saved. Close it and open it again — nothing was written.</summary>
    public static string RedactFailed => Get("RedactFailed");

    /// <summary>Whiteout covers — it doesn't remove</summary>
    public static string WhiteoutCoversOnlyTitle => Get("WhiteoutCoversOnlyTitle");

    /// <summary>Anything under a whiteout is still in the file, and another app can copy or search it. To take it out of the file, use Redact.</summary>
    public static string WhiteoutCoversOnlyBody => Get("WhiteoutCoversOnlyBody");

    /// <summary>Page {0}, {1}: {2}</summary>
    public static string PageRegionDescriptionWithContent(object? arg0, object? arg1, object? arg2) => string.Format(CultureInfo.CurrentCulture, Get("PageRegionDescriptionWithContent"), arg0, arg1, arg2);

    /// <summary>Saved {0}</summary>
    public static string SavedAnnouncement(object? arg0) => string.Format(CultureInfo.CurrentCulture, Get("SavedAnnouncement"), arg0);

    /// <summary>Exported {0}</summary>
    public static string ExportedAnnouncement(object? arg0) => string.Format(CultureInfo.CurrentCulture, Get("ExportedAnnouncement"), arg0);

    /// <summary>More options</summary>
    public static string MoreOptions => Get("MoreOptions");

    /// <summary>Close more options</summary>
    public static string CloseMoreOptions => Get("CloseMoreOptions");

    /// <summary>Close tab</summary>
    public static string CloseTab => Get("CloseTab");

    /// <summary>Close window</summary>
    public static string CloseWindow => Get("CloseWindow");

    /// <summary>New window</summary>
    public static string NewWindow => Get("NewWindow");

    /// <summary>{0}, tab</summary>
    public static string TabAccessibleName(object? arg0) => string.Format(CultureInfo.CurrentCulture, Get("TabAccessibleName"), arg0);

    /// <summary>{0}, unsaved changes, tab</summary>
    public static string TabAccessibleNameUnsaved(object? arg0) => string.Format(CultureInfo.CurrentCulture, Get("TabAccessibleNameUnsaved"), arg0);
}
