#!/usr/bin/env python3
"""Generates the Android launcher icon from the same geometry as the iOS icon.

The app shipped with no launcher resources at all and no android:icon in the
manifest, so Android fell back to the default system icon. This draws the same
design as tools/gen_ios_icon.py — diagonal gradient, white document with a folded
corner, two text lines, calligraphic check — but split into the two layers an
adaptive icon needs, so the launcher can mask, shadow, and animate it.

minSdk is 26, so every device gets the adaptive icon; the legacy PNG mipmaps are
generated anyway for launchers and tooling that still read them.

Usage: python3 tools/gen_android_icons.py [android/app/src/main/res]
"""
import os
import sys

from PIL import Image, ImageDraw

S = 8                      # supersample of the 256-unit design space
TOP, BOTTOM = (0x0A, 0x5B, 0xC4), (0x0F, 0xA8, 0xC6)

# 108dp adaptive canvas per density, and the legacy square icon sizes.
ADAPTIVE = {"mdpi": 108, "hdpi": 162, "xhdpi": 216, "xxhdpi": 324, "xxxhdpi": 432}
LEGACY = {"mdpi": 48, "hdpi": 72, "xhdpi": 96, "xxhdpi": 144, "xxxhdpi": 192}


def lerp(a, b, t):
    return tuple(int(a[i] + (b[i] - a[i]) * t) for i in range(3))


def pt(x, y):
    return (x * S, y * S)


def draw_gradient(size):
    img = Image.new("RGB", (size, size))
    px = img.load()
    for y in range(size):
        for x in range(0, size, 8):
            c = lerp(TOP, BOTTOM, (x + y) / (2 * size))
            for dx in range(8):
                px[x + dx, y] = c
    return img


def draw_document(d, notch_fill):
    """The document, fold, text lines and check — the iOS icon's foreground art.

    notch_fill is what shows through the cut corner: the gradient on the opaque
    icon, fully transparent on the adaptive foreground layer.
    """
    white = (255, 255, 255, 255)
    fold = (0xD6, 0xE7, 0xF8, 255)
    d.rounded_rectangle([pt(78, 52), pt(186, 204)], radius=14 * S, fill=white)
    d.polygon([pt(150, 52), pt(186, 52), pt(186, 88)], fill=notch_fill)
    d.polygon([pt(150, 52), pt(186, 88), pt(150, 88)], fill=white)
    d.polygon([pt(150, 52), pt(186, 88), pt(164, 88), pt(150, 74)], fill=fold)

    line = (0xC9, 0xDC, 0xEF, 255)
    for x0, x1, y in ((96, 138, 96), (96, 166, 118)):
        d.line([pt(x0, y), pt(x1, y)], fill=line, width=9 * S)
        for x in (x0, x1):
            d.ellipse([x * S - 4 * S, y * S - 4 * S, x * S + 4 * S, y * S + 4 * S], fill=line)

    def cubic(p0, p1, p2, p3, n=64):
        out = []
        for i in range(n + 1):
            t, mt = i / n, 1 - i / n
            out.append((mt**3 * p0[0] + 3 * mt**2 * t * p1[0] + 3 * mt * t**2 * p2[0] + t**3 * p3[0],
                        mt**3 * p0[1] + 3 * mt**2 * t * p1[1] + 3 * mt * t**2 * p2[1] + t**3 * p3[1]))
        return out

    path = cubic((92, 148), (100, 152), (110, 161), (122, 172)) + [(168, 104)]
    c0, c1 = (0x0E, 0x6F, 0xD8), (0x18, 0xB6, 0xC8)
    r = 6 * S
    for i in range(len(path) - 1):
        color = lerp(c0, c1, i / (len(path) - 1)) + (255,)
        a, b = path[i], path[i + 1]
        d.line([pt(*a), pt(*b)], fill=color, width=12 * S)
        d.ellipse([a[0] * S - r, a[1] * S - r, a[0] * S + r, a[1] * S + r], fill=color)
    last = path[-1]
    d.ellipse([last[0] * S - r, last[1] * S - r, last[0] * S + r, last[1] * S + r], fill=c1 + (255,))


def legacy_icon(size):
    """Opaque square icon: gradient plus art, exactly like the iOS one."""
    img = draw_gradient(256 * S).convert("RGBA")
    d = ImageDraw.Draw(img)
    draw_document(d, notch_fill=lerp(TOP, BOTTOM, (150 + 52) / 512.0) + (255,))
    return img.resize((size, size), Image.LANCZOS)


def foreground(size):
    """Art alone on transparency, scaled into the adaptive icon's safe zone.

    An adaptive foreground is a 108dp canvas whose outer 18dp on each side can be
    cropped by any mask, so the art has to sit inside the central 72dp. The design
    is 152 units tall (y 52..204); mapping that to 66dp leaves a little air.
    """
    art = Image.new("RGBA", (256 * S, 256 * S), (0, 0, 0, 0))
    draw_document(ImageDraw.Draw(art), notch_fill=(0, 0, 0, 0))
    art = art.crop((78 * S, 52 * S, 186 * S, 204 * S))       # tight to the document
    target_h = int(size * 66 / 108)
    target_w = max(1, int(art.width * target_h / art.height))
    art = art.resize((target_w, target_h), Image.LANCZOS)
    canvas = Image.new("RGBA", (size, size), (0, 0, 0, 0))
    canvas.paste(art, ((size - target_w) // 2, (size - target_h) // 2), art)
    return canvas


ADAPTIVE_XML = """<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by tools/gen_android_icons.py — do not hand-edit. -->
<adaptive-icon xmlns:android="http://schemas.android.com/apk/res/android">
    <background android:drawable="@drawable/ic_launcher_background" />
    <foreground android:drawable="@mipmap/ic_launcher_foreground" />
    <!-- No <monochrome>: the art is fully opaque, so a themed icon would render as
         a featureless document-shaped blob. Without it Android themes the normal
         adaptive icon instead. -->
</adaptive-icon>
"""

BACKGROUND_XML = """<?xml version="1.0" encoding="utf-8"?>
<!-- The icon's diagonal brand gradient, as the adaptive icon's background layer.
     Generated by tools/gen_android_icons.py — do not hand-edit. -->
<shape xmlns:android="http://schemas.android.com/apk/res/android" android:shape="rectangle">
    <gradient
        android:startColor="#0A5BC4"
        android:endColor="#0FA8C6"
        android:angle="315"
        android:type="linear" />
</shape>
"""


def main(res):
    for density, size in ADAPTIVE.items():
        d = os.path.join(res, f"mipmap-{density}")
        os.makedirs(d, exist_ok=True)
        foreground(size).save(os.path.join(d, "ic_launcher_foreground.png"))
        legacy = legacy_icon(LEGACY[density])
        legacy.convert("RGB").save(os.path.join(d, "ic_launcher.png"))
        legacy.convert("RGB").save(os.path.join(d, "ic_launcher_round.png"))

    anydpi = os.path.join(res, "mipmap-anydpi-v26")
    os.makedirs(anydpi, exist_ok=True)
    for name in ("ic_launcher.xml", "ic_launcher_round.xml"):
        open(os.path.join(anydpi, name), "w", encoding="utf-8").write(ADAPTIVE_XML)

    drawable = os.path.join(res, "drawable")
    os.makedirs(drawable, exist_ok=True)
    open(os.path.join(drawable, "ic_launcher_background.xml"), "w", encoding="utf-8").write(BACKGROUND_XML)

    print(f"wrote launcher icons into {res}")


if __name__ == "__main__":
    main(sys.argv[1] if len(sys.argv) > 1 else "android/app/src/main/res")
