#!/usr/bin/env python3
"""Generate the typed string accessors for the two desktop apps, and the
pseudo-locale used to check layouts before a translation exists (#91).

The English catalogue is the source of truth on each desktop platform:

    src/MegaPDF.App/Strings/en-US/Resources.resw      (Windows, MRT / x:Uid)
    src/MegaPDF.Avalonia/Strings/Strings.resx         (macOS, ResourceManager)

Neither `dotnet build` runs a ResX designer generator without Visual Studio,
so this script writes the accessor class instead. Run from anywhere:

    python3 tools/gen_strings.py            # regenerate both Strings.g.cs
    python3 tools/gen_strings.py pseudo     # also write the qps-ploc catalogues

Outputs (committed, checked for drift by ci.yml):
    src/MegaPDF.App/Strings.g.cs
    src/MegaPDF.Avalonia/Strings.g.cs

`pseudo` outputs (gitignored, never shipped) — accented, ~30 % longer copies of
the English so hard-coded strings and clipped layouts show up before the
French does:
    src/MegaPDF.App/Strings/qps-ploc/Resources.resw
    src/MegaPDF.Avalonia/Strings/Strings.qps-ploc.resx

Conventions the generator relies on:
  * A key containing a dot (`LabelOpen.Text`) is a XAML x:Uid property and gets
    no accessor — XAML resolves it directly.
  * A value containing `{0}`-style placeholders becomes a method taking one
    argument per placeholder and formatting with CurrentCulture.
  * Everything else is a static property.
"""

import re
import sys
import xml.etree.ElementTree as ET
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent

WINDOWS_RESW = ROOT / "src/MegaPDF.App/Strings/en-US/Resources.resw"
WINDOWS_OUT = ROOT / "src/MegaPDF.App/Strings.g.cs"
WINDOWS_PSEUDO = ROOT / "src/MegaPDF.App/Strings/qps-ploc/Resources.resw"

MAC_RESX = ROOT / "src/MegaPDF.Avalonia/Strings/Strings.resx"
MAC_OUT = ROOT / "src/MegaPDF.Avalonia/Strings.g.cs"
MAC_PSEUDO = ROOT / "src/MegaPDF.Avalonia/Strings/Strings.qps-ploc.resx"

PLACEHOLDER = re.compile(r"\{(\d+)(?:[:,][^}]*)?\}")


def read_catalogue(path: Path) -> list[tuple[str, str, str]]:
    """(name, value, comment) for every <data> entry, in file order."""
    entries = []
    for data in ET.parse(path).getroot().findall("data"):
        name = data.get("name")
        value = data.findtext("value") or ""
        comment = data.findtext("comment") or ""
        entries.append((name, value, comment))
    return entries


def accessor(name: str, value: str) -> str:
    slots = sorted({int(n) for n in PLACEHOLDER.findall(value)})
    summary = value.replace("\n", " ").replace("&", "&amp;").replace("<", "&lt;")
    lines = [f"    /// <summary>{summary}</summary>"]
    if not slots:
        lines.append(f"    public static string {name} => Get(\"{name}\");")
    else:
        expected = list(range(len(slots)))
        if slots != expected:
            raise SystemExit(f"{name}: placeholders must be {{0}}..{{n}} without gaps, got {slots}")
        params = ", ".join(f"object? arg{i}" for i in slots)
        args = ", ".join(f"arg{i}" for i in slots)
        lines.append(
            f"    public static string {name}({params}) => "
            f"string.Format(CultureInfo.CurrentCulture, Get(\"{name}\"), {args});"
        )
    return "\n".join(lines)


def generate(entries, namespace: str, source: str, loader: str) -> str:
    body = "\n\n".join(accessor(n, v) for n, v, _ in entries if "." not in n)
    return f"""// <auto-generated>
//   Generated by tools/gen_strings.py from {source}.
//   Do not edit: change the catalogue and re-run the script.
// </auto-generated>
#nullable enable
using System.Globalization;

namespace {namespace};

/// <summary>
/// Typed access to the English catalogue's keys (#91). Every user-facing string
/// in code goes through here, so a missing key is a compile error rather than a
/// runtime blank.
/// </summary>
public static partial class Strings
{{
{loader}

{body}
}}
"""


WINDOWS_LOADER = """    private static string Get(string key) => AppLanguage.GetString(key);"""

MAC_LOADER = """    private static readonly System.Resources.ResourceManager Manager =
        new("MegaPDF.Avalonia.Strings.Strings", typeof(Strings).Assembly);

    private static string Get(string key) =>
        Manager.GetString(key, CultureInfo.CurrentUICulture) ?? key;"""


# --- pseudo-localisation -----------------------------------------------------

ACCENTS = str.maketrans(
    "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ",
    "åƀçđéƒģĥïĵķļɱñöþqŕşŧûṽŵẋÿžÅƁÇĐÉƑĢĤÏĴĶĻɱÑÖÞQŔŞŦÛṼŴẊŸŽ",
)


def pseudo(value: str) -> str:
    """Accent every letter, keep placeholders intact, pad by ~30 %."""
    out = []
    last = 0
    for m in PLACEHOLDER.finditer(value):
        out.append(value[last:m.start()].translate(ACCENTS))
        out.append(m.group(0))
        last = m.end()
    out.append(value[last:].translate(ACCENTS))
    text = "".join(out)
    pad = "~" * max(1, round(len(value) * 0.3))
    return f"[{text}{pad}]"


def write_pseudo(source: Path, target: Path) -> None:
    tree = ET.parse(source)
    for data in tree.getroot().findall("data"):
        v = data.find("value")
        if v is not None and v.text:
            v.text = pseudo(v.text)
    target.parent.mkdir(parents=True, exist_ok=True)
    tree.write(target, encoding="utf-8", xml_declaration=True)


def main(argv: list[str]) -> int:
    for resx, out, ns, loader in (
        (WINDOWS_RESW, WINDOWS_OUT, "MegaPDF.App", WINDOWS_LOADER),
        (MAC_RESX, MAC_OUT, "MegaPDF.Avalonia", MAC_LOADER),
    ):
        if not resx.exists():
            print(f"skip: {resx.relative_to(ROOT)} does not exist")
            continue
        entries = read_catalogue(resx)
        out.write_text(generate(entries, ns, resx.relative_to(ROOT).as_posix(), loader), encoding="utf-8", newline="\n")
        print(f"{out.relative_to(ROOT)}: {sum(1 for n, _, _ in entries if '.' not in n)} accessors")

    if "pseudo" in argv:
        for src, dst in ((WINDOWS_RESW, WINDOWS_PSEUDO), (MAC_RESX, MAC_PSEUDO)):
            if src.exists():
                write_pseudo(src, dst)
                print(f"{dst.relative_to(ROOT)}: pseudo-locale written")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
