#!/usr/bin/env python3
"""Microsoft Store submission through the Store submission API (#146 §4).

Partner Center's own REST API, driven by the Microsoft Entra application
"MegaPDF submission" (Manager role). Nothing here opens a browser; nothing here
prints a credential, a token or the upload URL.

Credentials come from a KEY=VALUE file, never from argv or the environment dump:
MSSTORE_ENV_FILE if set, else ~/.secrets/megapdf-msstore.env (0600), holding
MSSTORE_TENANT_ID, MSSTORE_CLIENT_ID and MSSTORE_CLIENT_SECRET (MSSTORE_SELLER_ID
may sit beside them; this API does not need it).

  msstore_submit.py build        write payload.json + upload.zip under --out; no network
  msstore_submit.py token-test   sign in and print only "token OK" or the HTTP status
  msstore_submit.py status       read back the app, its published and pending submissions
  msstore_submit.py plan         apply the payload to a copy of the published submission,
                                 locally, and print what would change; creates nothing
  msstore_submit.py submit       create the submission, fill it, upload, commit, poll
  msstore_submit.py poll ID      poll a submission's status until certification starts

Content is read from the repo, never typed here: the listing copy from
docs/microsoft-store-listing.md (generated by tools/gen_listing_copy.py), What's
new from docs/release-notes/<ver>/microsoft-store.md, screenshots from
artifacts/store/screenshots/<lang>/0N-*.png and the packages from
artifacts/store/rc-<ver>/, each checked against that folder's SHA256SUMS.
"""
import argparse
import hashlib
import json
import os
import re
import sys
import time
import urllib.error
import urllib.parse
import urllib.request
import zipfile
from pathlib import Path

APP_ID = "9PF4TRRH4M76"          # Store ID of "Mega PDF"
TITLE = "Mega PDF"               # must match the name reserved in Partner Center
API = "https://manage.devcenter.microsoft.com/v1.0/my"
RESOURCE = "https://manage.devcenter.microsoft.com"
VERSION = "2.0.0.0"
REPO = Path(__file__).resolve().parent.parent

# Partner Center listing language -> the screenshot set and the release-notes block
LANGS = {
    "en-us": {"shots": "en", "doc": "en-US"},
    "en-ca": {"shots": "en", "doc": "en-CA"},
    "fr-ca": {"shots": "fr-CA", "doc": "fr-CA"},
    "fr-fr": {"shots": "fr-FR", "doc": "fr-FR"},
}
LIMITS = {"description": 10000, "shortDescription": 1000, "releaseNotes": 1500,
          "feature": 200, "features": 20, "keyword": 30, "keywords": 7,
          "keywordWords": 21, "caption": 200, "copyright": 200}

CERT_NOTES = (
    "MegaPDF 2.0 is a local PDF editor: no account, no sign-in, no network use. "
    "To try it, open any PDF (File > Open, or double-click a .pdf once the app is the "
    "default). Click text to edit it, click an empty square to tick it, use Redact to "
    "remove a name from the file, and Save. This submission replaces both 1.7 packages: "
    "the new ARM64 package carries ARM64 native libraries (the 1.7 ARM64 package did not "
    "and could not open documents)."
)


def die(msg):
    print(f"error: {msg}", file=sys.stderr)
    sys.exit(1)


# ---------------------------------------------------------------- content

def fenced_after(lines, i):
    """Text of the first ``` block at or after line i, and the index past it."""
    while i < len(lines) and not lines[i].startswith("```"):
        i += 1
    if i >= len(lines):
        return None, i
    j = i + 1
    body = []
    while j < len(lines) and not lines[j].startswith("```"):
        body.append(lines[j])
        j += 1
    return "\n".join(body).strip("\n"), j + 1


def parse_listing_doc(path):
    text = path.read_text(encoding="utf-8")
    m = re.search(r"<!-- copy-by-language -->(.*)<!-- /copy-by-language -->", text, re.S)
    if not m:
        die(f"{path}: no copy-by-language section")
    out = {}
    for sect in re.split(r"^### ", m.group(1), flags=re.M)[1:]:
        code = re.search(r"`([a-z]{2}-[A-Z]{2})`", sect.splitlines()[0])
        if not code:
            continue
        lines = sect.splitlines()
        fields = {}
        i = 0
        while i < len(lines):
            head = re.match(r"\*\*([^*]+)\*\*", lines[i])
            if head:
                body, i = fenced_after(lines, i + 1)
                fields[head.group(1).strip()] = body
                continue
            i += 1
        def pick(prefix):
            for k, v in fields.items():
                if k.startswith(prefix):
                    return v
            die(f"{path}: {code.group(1)} has no '{prefix}' block")
        captions = {}
        for line in pick("Screenshot captions").splitlines():
            name, _, cap = line.partition(": ")
            captions[name.strip()] = cap.strip()
        out[code.group(1)] = {
            "shortDescription": pick("Short description"),
            "description": pick("Description"),
            "features": [l.strip() for l in pick("App features").splitlines() if l.strip()],
            "keywords": [l.strip() for l in pick("Search terms").splitlines() if l.strip()],
            "copyright": pick("Copyright"),
            "captions": captions,
        }
    other = text.split("## Other fields", 1)[1].split("\n## ", 1)[0].splitlines()
    vals = []
    i = 0
    while len(vals) < 3:
        body, i = fenced_after(other, i)
        if body is None:
            die(f"{path}: Other fields has fewer than three blocks")
        vals.append(body.strip())
    return out, {"privacyPolicy": vals[0], "websiteUrl": vals[1], "supportContact": vals[2]}


def parse_release_notes(path):
    lines = path.read_text(encoding="utf-8").splitlines()
    notes = {}
    codes = []
    i = 0
    while i < len(lines):
        if lines[i].startswith("## "):
            codes = re.findall(r"`([a-z]{2}-[A-Z]{2})`", lines[i])
        if codes and lines[i].startswith("```"):
            body, i = fenced_after(lines, i)
            for c in codes:
                notes[c] = body
            codes = []
            continue
        i += 1
    return notes


def check_packages(rc_dir):
    """The two upload packages, each matching its line in rc_dir/SHA256SUMS."""
    sums = {}
    for line in (rc_dir / "SHA256SUMS").read_text().splitlines():
        parts = line.split()
        if len(parts) == 2 and not line.startswith("#") and "not-for-upload" not in parts[1]:
            sums[Path(parts[1]).name] = parts[0]
    pkgs = []
    for arch in ("x64", "arm64"):
        p = rc_dir / f"MegaPDF.App_{VERSION}_{arch}.msix"
        if not p.is_file():
            die(f"missing {p}")
        h = hashlib.sha256(p.read_bytes()).hexdigest()
        if sums.get(p.name) != h:
            die(f"{p.name}: sha256 {h[:12]}… does not match SHA256SUMS")
        pkgs.append((p, h))
    return pkgs


def build_payload(out, art):
    listing, other = parse_listing_doc(REPO / "docs/microsoft-store-listing.md")
    ver = VERSION.rsplit(".", 2)[0]  # 2.0
    notes = parse_release_notes(REPO / f"docs/release-notes/{ver}/microsoft-store.md")
    pkgs = check_packages(art / f"rc-{VERSION}")
    problems = []
    payload = {"appId": APP_ID, "version": VERSION, "targetPublishMode": "Immediate",
               "notesForCertification": CERT_NOTES, "packages": [], "listings": {}}
    files = []
    for p, h in pkgs:
        rel = f"packages/{p.name}"
        payload["packages"].append({"fileName": rel, "sha256": h})
        files.append((p, rel))
    for lang, m in LANGS.items():
        src = listing.get(m["doc"]) or die(f"listing doc has no {m['doc']}")
        rn = notes.get(m["doc"]) or die(f"release notes have no {m['doc']}")
        shots = sorted((art / "screenshots" / m["shots"]).glob("0[1-9]-*.png"))
        if [s.name for s in shots] != list(src["captions"]):
            problems.append(f"{lang}: screenshots {[s.name for s in shots]} "
                            f"!= captions {list(src['captions'])}")
        images = []
        for s in shots:
            rel = f"images/{m['shots']}/{s.name}"
            if (s, rel) not in files:
                files.append((s, rel))
            images.append({"fileName": rel, "description": src["captions"].get(s.name, "")})
        base = {
            "title": TITLE,
            "shortDescription": src["shortDescription"],
            "description": src["description"],
            "features": src["features"],
            "keywords": src["keywords"],
            "releaseNotes": rn,
            "copyrightAndTrademarkInfo": src["copyright"],
            **other,
            "images": images,
        }
        for k in ("description", "shortDescription", "releaseNotes"):
            if len(base[k]) > LIMITS[k]:
                problems.append(f"{lang}: {k} {len(base[k])} > {LIMITS[k]}")
        if len(base["copyrightAndTrademarkInfo"]) > LIMITS["copyright"]:
            problems.append(f"{lang}: copyright too long")
        if len(base["features"]) > LIMITS["features"]:
            problems.append(f"{lang}: {len(base['features'])} features > {LIMITS['features']}")
        for f in base["features"]:
            if len(f) > LIMITS["feature"]:
                problems.append(f"{lang}: feature {len(f)} > {LIMITS['feature']}: {f[:40]}…")
        if len(base["keywords"]) > LIMITS["keywords"]:
            problems.append(f"{lang}: {len(base['keywords'])} search terms > {LIMITS['keywords']}")
        for k in base["keywords"]:
            if len(k) > LIMITS["keyword"]:
                problems.append(f"{lang}: search term {len(k)} > {LIMITS['keyword']}: {k}")
        words = sum(len(k.split()) for k in base["keywords"])
        if words > LIMITS["keywordWords"]:
            problems.append(f"{lang}: search terms use {words} words > {LIMITS['keywordWords']}")
        for im in images:
            if len(im["description"]) > LIMITS["caption"]:
                problems.append(f"{lang}: caption {len(im['description'])} > {LIMITS['caption']}")
            if not im["description"]:
                problems.append(f"{lang}: {im['fileName']} has no caption")
        payload["listings"][lang] = base
    if problems:
        die("content check failed:\n  " + "\n  ".join(problems))
    out.mkdir(parents=True, exist_ok=True)
    (out / "payload.json").write_text(json.dumps(payload, ensure_ascii=False, indent=2), encoding="utf-8")
    zpath = out / "upload.zip"
    with zipfile.ZipFile(zpath, "w", zipfile.ZIP_STORED) as z:
        for src, rel in files:
            z.write(src, rel)
    return payload, zpath


def summarize(payload, zpath=None):
    print(f"app {payload['appId']}  version {payload['version']}  publish {payload['targetPublishMode']}")
    for p in payload["packages"]:
        print(f"  package {p['fileName']}  sha256 {p['sha256'][:12]}…")
    for lang, b in payload["listings"].items():
        print(f"  {lang}: title '{b['title']}', description {len(b['description'])}/10000, "
              f"short {len(b['shortDescription'])}, what's new {len(b['releaseNotes'])}/1500, "
              f"{len(b['features'])} features (longest {max(map(len, b['features']))}/200), "
              f"{len(b['keywords'])} search terms (longest {max(map(len, b['keywords']))}/30), "
              f"{len(b['images'])} screenshots")
    if zpath:
        with zipfile.ZipFile(zpath) as z:
            n = len(z.namelist())
        print(f"  upload.zip: {n} files, {zpath.stat().st_size / 1e6:.1f} MB")


# ---------------------------------------------------------------- API

def load_creds():
    path = Path(os.environ.get("MSSTORE_ENV_FILE") or Path.home() / ".secrets/megapdf-msstore.env")
    if not path.is_file():
        die("credentials file not found (set MSSTORE_ENV_FILE or create ~/.secrets/megapdf-msstore.env)")
    creds = {}
    for line in path.read_text().splitlines():
        line = line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        k, _, v = line.partition("=")
        creds[k.strip()] = v.strip().strip('"').strip("'")
    missing = [k for k in ("MSSTORE_TENANT_ID", "MSSTORE_CLIENT_ID", "MSSTORE_CLIENT_SECRET")
               if not creds.get(k)]
    if missing:
        die("credentials file lacks " + ", ".join(missing))
    return creds


_TOKEN = None


def token():
    global _TOKEN
    if _TOKEN:
        return _TOKEN
    c = load_creds()
    body = urllib.parse.urlencode({
        "grant_type": "client_credentials", "client_id": c["MSSTORE_CLIENT_ID"],
        "client_secret": c["MSSTORE_CLIENT_SECRET"], "resource": RESOURCE}).encode()
    url = f"https://login.microsoftonline.com/{urllib.parse.quote(c['MSSTORE_TENANT_ID'])}/oauth2/token"
    try:
        with urllib.request.urlopen(urllib.request.Request(url, data=body), timeout=60) as r:
            _TOKEN = json.load(r)["access_token"]
    except urllib.error.HTTPError as e:
        try:
            err = json.load(e)
            detail = f"{err.get('error')}: {err.get('error_description', '').splitlines()[0]}"
        except Exception:
            detail = ""
        die(f"sign-in failed, HTTP {e.code} {detail}")
    return _TOKEN


def api(method, path, body=None, ok=(200, 201, 204)):
    url = path if path.startswith("https://") else API + path
    data = json.dumps(body).encode() if body is not None else None
    req = urllib.request.Request(url, data=data, method=method, headers={
        "Authorization": f"Bearer {token()}", "Content-Type": "application/json"})
    for attempt in range(4):
        try:
            with urllib.request.urlopen(req, timeout=120) as r:
                raw = r.read()
                return json.loads(raw) if raw else None
        except urllib.error.HTTPError as e:
            raw = e.read().decode("utf-8", "replace")
            if e.code in (429, 500, 502, 503) and attempt < 3:
                time.sleep(10 * (attempt + 1))
                continue
            die(f"{method} {path} -> HTTP {e.code}: {raw[:1500]}")


def redacted(sub):
    s = json.loads(json.dumps(sub))
    if "fileUploadUrl" in s:
        s["fileUploadUrl"] = "<redacted SAS URL>"
    return s


def describe_submission(sub, label):
    print(f"{label}: id {sub.get('id')}  status {sub.get('status')}  "
          f"publish {sub.get('targetPublishMode')}")
    for p in sub.get("applicationPackages", []):
        print(f"  package {p.get('fileName')}  v{p.get('version')}  {p.get('architecture')}  "
              f"{p.get('fileStatus')}  langs {','.join(p.get('languages') or [])}")
    for lang, l in sorted(sub.get("listings", {}).items()):
        b = l.get("baseListing", {})
        imgs = [i for i in b.get("images", []) if i.get("imageType") == "Screenshot"]
        print(f"  {lang}: title '{b.get('title')}', description {len(b.get('description') or '')}, "
              f"what's new {len(b.get('releaseNotes') or '')}, {len(b.get('features') or [])} features, "
              f"{len(b.get('keywords') or [])} search terms, {len(imgs)} screenshots "
              f"({', '.join(sorted(set(i.get('fileStatus', '?') for i in imgs)))})")
    pr = sub.get("pricing", {})
    print(f"  pricing {pr.get('priceId')}  visibility {sub.get('visibility')}")


def cmd_status(_args):
    app = api("GET", f"/applications/{APP_ID}")
    print(f"app {app.get('id')}  '{app.get('primaryName')}'  package family {app.get('packageFamilyName')}")
    pub = app.get("lastPublishedApplicationSubmission")
    pend = app.get("pendingApplicationSubmission")
    if pub:
        describe_submission(api("GET", f"/applications/{APP_ID}/submissions/{pub['id']}"),
                            "published submission")
    if pend:
        sub = api("GET", f"/applications/{APP_ID}/submissions/{pend['id']}")
        describe_submission(sub, "PENDING submission")
        st = api("GET", f"/applications/{APP_ID}/submissions/{pend['id']}/status")
        print(f"  status {st.get('status')}  details {json.dumps(st.get('statusDetails'))[:1500]}")
    else:
        print("no pending submission")


def apply_payload(sub, payload):
    """Mutate a submission JSON so it carries this release."""
    for p in sub.get("applicationPackages", []):
        p["fileStatus"] = "PendingDelete"
    for p in payload["packages"]:
        sub.setdefault("applicationPackages", []).append({
            "fileName": p["fileName"], "fileStatus": "PendingUpload",
            "minimumDirectXVersion": "None", "minimumSystemRam": "None"})
    sub["targetPublishMode"] = "Immediate"
    sub["targetPublishDate"] = None
    sub["notesForCertification"] = payload["notesForCertification"]
    listings = sub.setdefault("listings", {})
    for lang, want in payload["listings"].items():
        l = listings.setdefault(lang, {"baseListing": {}, "platformOverrides": {}})
        b = l.setdefault("baseListing", {})
        for im in b.get("images", []):
            if im.get("imageType") == "Screenshot":
                im["fileStatus"] = "PendingDelete"
        for k, v in want.items():
            if k != "images":
                b[k] = v
        b.setdefault("images", []).extend(
            {"fileName": im["fileName"], "fileStatus": "PendingUpload",
             "description": im["description"], "imageType": "Screenshot"}
            for im in want["images"])
    return sub


def cmd_plan(args):
    payload, _ = build_payload(Path(args.out), Path(args.artifacts) / "store")
    app = api("GET", f"/applications/{APP_ID}")
    pub = app.get("lastPublishedApplicationSubmission") or die("no published submission to base on")
    sub = api("GET", f"/applications/{APP_ID}/submissions/{pub['id']}")
    describe_submission(sub, "published (before)")
    describe_submission(apply_payload(sub, payload), "planned (after)")
    extra = sorted(set(sub.get("listings", {})) - set(payload["listings"]))
    if extra:
        print(f"  note: listings not touched by this payload: {', '.join(extra)}")


def upload(zpath, sas):
    size = zpath.stat().st_size
    with open(zpath, "rb") as f:
        req = urllib.request.Request(sas, data=f, method="PUT", headers={
            "x-ms-blob-type": "BlockBlob", "x-ms-version": "2020-04-08",
            "Content-Length": str(size), "Content-Type": "application/zip"})
        try:
            with urllib.request.urlopen(req, timeout=3600) as r:
                print(f"uploaded {size / 1e6:.1f} MB, HTTP {r.status}")
        except urllib.error.HTTPError as e:
            die(f"upload failed, HTTP {e.code}: {e.read()[:500]!r}")


def cmd_poll(args, sid=None):
    sid = sid or args.id
    last = None
    deadline = time.time() + args.timeout
    while True:
        st = api("GET", f"/applications/{APP_ID}/submissions/{sid}/status")
        s = st.get("status")
        if s != last:
            print(f"{time.strftime('%H:%M:%S')} {s}")
            last = s
        det = st.get("statusDetails") or {}
        if s == "CommitFailed" or det.get("errors"):
            print(json.dumps(det, indent=2)[:4000])
            if s == "CommitFailed":
                sys.exit(2)
        if s not in ("CommitStarted", "PendingCommit", "PreProcessing"):
            if det.get("warnings"):
                print("warnings:", json.dumps(det["warnings"], indent=2)[:3000])
            return s
        if time.time() > deadline:
            die(f"still {s} after {args.timeout}s; poll again with: msstore_submit.py poll {sid}")
        time.sleep(30)


def cmd_submit(args):
    payload, zpath = build_payload(Path(args.out), Path(args.artifacts) / "store")
    summarize(payload, zpath)
    app = api("GET", f"/applications/{APP_ID}")
    if app.get("pendingApplicationSubmission"):
        die(f"a pending submission already exists ({app['pendingApplicationSubmission']['id']}); "
            "inspect it with `status` and delete it in Partner Center (or via the API) first")
    sub = api("POST", f"/applications/{APP_ID}/submissions")
    sid = sub["id"]
    print(f"created submission {sid}")
    sas = sub["fileUploadUrl"]
    sub = apply_payload(sub, payload)
    updated = api("PUT", f"/applications/{APP_ID}/submissions/{sid}", sub)
    describe_submission(updated, "updated")
    (Path(args.out) / "submission.json").write_text(
        json.dumps(redacted(updated), ensure_ascii=False, indent=2), encoding="utf-8")
    upload(zpath, sas)
    api("POST", f"/applications/{APP_ID}/submissions/{sid}/commit")
    print(f"committed {sid}")
    final = cmd_poll(args, sid)
    print(f"submission {sid}: {final}")


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("command", choices=["build", "token-test", "status", "plan", "submit", "poll"])
    ap.add_argument("id", nargs="?")
    ap.add_argument("--artifacts", default=str(REPO / "artifacts"),
                    help="the artifacts folder holding store/rc-<ver>/ and store/screenshots/")
    ap.add_argument("--out", help="where payload.json, upload.zip and submission.json go "
                    "(default <artifacts>/store/msstore-<ver>)")
    ap.add_argument("--timeout", type=int, default=3600)
    args = ap.parse_args()
    args.out = args.out or str(Path(args.artifacts) / f"store/msstore-{VERSION}")
    if args.command == "build":
        payload, zpath = build_payload(Path(args.out), Path(args.artifacts) / "store")
        summarize(payload, zpath)
    elif args.command == "token-test":
        token()
        print("token OK")
    elif args.command == "status":
        cmd_status(args)
    elif args.command == "plan":
        cmd_plan(args)
    elif args.command == "submit":
        cmd_submit(args)
    elif args.command == "poll":
        if not args.id:
            die("poll needs a submission id")
        cmd_poll(args)


if __name__ == "__main__":
    main()
